// Bộ câu hỏi môn Sinh học - biên tập theo nội dung trong pages/ly-thuyết.html
// Mỗi câu: { q, options, a, explain, topic }
const questions_sinh = [
	// --- PHÂN TỬ (ADN, ARN, bản sao, phiên mã, dịch mã, đột biến)
	{ q: "ADN có cấu trúc gì?", options: ["A. Mạch đơn", "B. Cầu thang xoắn (xoắn kép)", "C. Mạch vòng", "D. Lưới"], a: "B. Cầu thang xoắn (xoắn kép)", explain: "ADN có cấu trúc xoắn kép do Watson và Crick mô tả.", topic: "Phân tử" },
	{ q: "Đơn vị cấu tạo của ADN là gì?", options: ["A. Amino acid", "B. Glucose", "C. Nuclêôtit", "D. Lipid"], a: "C. Nuclêôtit", explain: "Nuclêôtit gồm bazơ nitơ, đường deoxyribose và nhóm phosphate.", topic: "Phân tử" },
	{ q: "Nguyên tắc bắt cặp bazơ trong ADN là gì?", options: ["A. A–G, T–C", "B. A–T, G–C", "C. A–U, G–C", "D. A–C, G–T"], a: "B. A–T, G–C", explain: "A liên kết với T bằng 2 liên kết hidro; G liên kết với C bằng 3 liên kết hidro.", topic: "Phân tử" },
	{ q: "Phiên mã là quá trình nào?", options: ["A. ADN → ARN", "B. ARN → ADN", "C. ARN → protein", "D. ADN tự nhân đôi"], a: "A. ADN → ARN", explain: "Phiên mã diễn ra trong nhân, tạo mRNA từ gen trên ADN.", topic: "Phân tử" },
	{ q: "Dịch mã xảy ra ở đâu và tạo ra gì?", options: ["A. Ở nhân, tạo ADN", "B. Ở ribôxôm, tạo prôtêin", "C. Ở màng tế bào, tạo lipid", "D. Ở ty thể, tạo ATP"], a: "B. Ở ribôxôm, tạo prôtêin", explain: "mRNA được dịch trên ribôxôm để tổng hợp chuỗi polypeptid.", topic: "Phân tử" },
	{ q: "Loại ARN nào vận chuyển axit amin tới ribôxôm?", options: ["A. mARN", "B. rARN", "C. tARN", "D. snARN"], a: "C. tARN", explain: "tARN mang axit amin và khớp với codon trên mARN.", topic: "Phân tử" },
	{ q: "Đột biến gen là gì?", options: ["A. Thay đổi số lượng tế bào", "B. Thay đổi nhỏ trong trình tự ADN", "C. Thay đổi thành phần nước", "D. Biến đổi môi trường"], a: "B. Thay đổi nhỏ trong trình tự ADN", explain: "Đột biến có thể có lợi, có hại hoặc trung tính.", topic: "Phân tử" },
	{ q: "ADN viết tắt của từ gì?", options: ["A. Axit Đeoxyribo Nucleic", "B. Axit Ribo Nucleic", "C. Axit Amino", "D. Axit Lipid"], a: "A. Axit Đeoxyribo Nucleic", explain: "ADN là Axit Đeoxyribo Nucleic.", topic: "Phân tử" },
	{ q: "mARN có vai trò chính là gì?", options: ["A. Vận chuyển axit amin", "B. Mang thông tin di truyền từ ADN tới ribôxôm", "C. Tạo thành ribôxôm", "D. Phá hủy protein"], a: "B. Mang thông tin di truyền từ ADN tới ribôxôm", explain: "mARN mang mã di truyền ra cytoplasm để dịch mã.", topic: "Phân tử" },
	{ q: "Bazơ nào không xuất hiện trong ARN?", options: ["A. A", "B. T", "C. G", "D. U"], a: "B. T", explain: "Trong ARN thay T bằng U (uracil).", topic: "Phân tử" },
	{ q: "Đơn vị cấu tạo của ARN là gì?", options: ["A. Nuclêôtit", "B. Amino acid", "C. Glucose", "D. Nước"], a: "A. Nuclêôtit", explain: "ARN cũng được cấu tạo từ nuclêôtit.", topic: "Phân tử" },
	{ q: "Phiên mã xảy ra ở cơ quan nào trong tế bào eukaryote?", options: ["A. Ribôxôm", "B. Nhân", "C. Ty thể", "D. Màng tế bào"], a: "B. Nhân", explain: "Phiên mã diễn ra trong nhân tế bào eukaryote.", topic: "Phân tử" },
	{ q: "Bao nhiêu loại ARN chính tham gia trực tiếp vào tổng hợp protein?", options: ["A. 1", "B. 2", "C. 3", "D. 4"], a: "C. 3", explain: "mARN, tARN và rARN tham gia tổng hợp protein.", topic: "Phân tử" },
	{ q: "Các codon trên mARN gồm bao nhiêu nucleotide?", options: ["A. 1", "B. 2", "C. 3", "D. 4"], a: "C. 3", explain: "Mỗi codon gồm 3 nucleotide mã hoá 1 axit amin.", topic: "Phân tử" },
	{ q: "Dịch mã bắt đầu từ codon nào phổ biến nhất?", options: ["A. UAA", "B. AUG", "C. UGA", "D. UAG"], a: "B. AUG", explain: "AUG mã hoá methionine và thường là codon khởi đầu.", topic: "Phân tử" },
	{ q: "TARN có chức năng gì?", options: ["A. Mang thông tin di truyền", "B. Mang axit amin tới ribôxôm", "C. Tổng hợp ribôxôm", "D. Kết hợp DNA"], a: "B. Mang axit amin tới ribôxôm", explain: "tARN mang axit amin phù hợp tới vị trí codon trên mARN.", topic: "Phân tử" },
	{ q: "Một nucleotide gồm những thành phần nào?", options: ["A. Bazơ nitơ, đường 5C, nhóm phosphate", "B. Amino acid và bazơ", "C. Lipid và đường", "D. Enzim và protein"], a: "A. Bazơ nitơ, đường 5C, nhóm phosphate", explain: "Nuclêôtit gồm bazơ, đường (ribose hoặc deoxyribose) và phosphate.", topic: "Phân tử" },
	{ q: "Loại liên kết giữa các bazơ bổ sung là gì?", options: ["A. Liên kết ion", "B. Liên kết disulfide", "C. Liên kết hidro", "D. Liên kết glycosidic"], a: "C. Liên kết hidro", explain: "Các bazơ liên kết bằng liên kết hidro giữa hai mạch.", topic: "Phân tử" },
	{ q: "Trong ADN, bazơ A liên kết với bazơ nào?", options: ["A. G", "B. C", "C. T", "D. U"], a: "C. T", explain: "A liên kết với T trong ADN.", topic: "Phân tử" },
	{ q: "Trình tự nucleotit của gen quyết định điều gì?", options: ["A. Hình dạng tế bào", "B. Trình tự axit amin của protein", "C. Số lượng mitochondria", "D. pH tế bào"], a: "B. Trình tự axit amin của protein", explain: "Trình tự nucleotit mã hoá trình tự axit amin qua mã di truyền.", topic: "Phân tử" },
	{ q: "Tại sao trong ARN có U thay vì T?", options: ["A. Vì ARN không có đường", "B. Vì U gắn với A ổn định hơn trong ARN", "C. Vì ARN dùng một loại bazơ khác", "D. Vì lỗi phân loại"], a: "B. Vì U gắn với A ổn định hơn trong ARN", explain: "Uracil thay thế thymine ở ARN; cấu trúc và sinh tổng hợp khác so với ADN.", topic: "Phân tử" },
	{ q: "Sự khác nhau cơ bản giữa ADN và ARN là gì?", options: ["A. ADN có ribose, ARN có deoxyribose", "B. ADN cấu trúc mạch đơn, ARN xoắn kép", "C. ADN có T, ARN có U và ADN có deoxyribose", "D. Không có khác nhau"], a: "C. ADN có T, ARN có U và ADN có deoxyribose", explain: "ADN có deoxyribose và thymine; ARN có ribose và uracil.", topic: "Phân tử" },
	{ q: "Tại sao phiên mã chỉ sao chép 1 bên mạch của ADN?", options: ["A. Vì enzyme không làm việc trên cả hai mạch cùng lúc", "B. Vì chỉ một mạch mang mã cho gen cụ thể", "C. Vì một mạch bị loại bỏ", "D. Vì mạch kia quá ngắn"], a: "B. Vì chỉ một mạch mang mã cho gen cụ thể", explain: "Chỉ mạch khuôn (template) mang thông tin cho mARN; mạch đối diện là mạch mã tương ứng.", topic: "Phân tử" },
	{ q: "Crossing-over ảnh hưởng tới phiên mã như thế nào?", options: ["A. Thay đổi trình tự gen trên ADN, có thể thay đổi sản phẩm phiên mã", "B. Ngừng phiên mã hoàn toàn", "C. Tăng số ribôxôm", "D. Không ảnh hưởng gì"], a: "A. Thay đổi trình tự gen trên ADN, có thể thay đổi sản phẩm phiên mã", explain: "Chuyển đoạn hay tái tổ hợp có thể thay đổi trình tự gen, ảnh hưởng đến phiên mã và sản phẩm.", topic: "Phân tử" },
	{ q: "Nếu một đoạn mARN bị cắt ngắn trước codon kết thúc, điều gì xảy ra?", options: ["A. Protein dài hơn dự kiến", "B. Protein ngắn hoặc bị ngừng sớm", "C. Không ảnh hưởng", "D. Tăng phiên mã"], a: "B. Protein ngắn hoặc bị ngừng sớm", explain: "mARN ngắn hơn dẫn đến mất codon, có thể tạo protein ngắn hoặc không đầy đủ.", topic: "Phân tử" },
	{ q: "Sự khác nhau giữa codon và anticodon là gì?", options: ["A. Codon nằm trên tARN, anticodon trên mARN", "B. Codon trên mARN mã hoá axit amin, anticodon trên tARN bắt cặp với codon", "C. Không khác nhau", "D. Codon là protein"], a: "B. Codon trên mARN mã hoá axit amin, anticodon trên tARN bắt cặp với codon", explain: "Anticodon giúp tARN mang axit amin đúng vị trí so với codon mARN.", topic: "Phân tử" },
	{ q: "Tại sao một đột biến điểm có thể không thay đổi protein?", options: ["A. Vì mã di truyền thoáng qua", "B. Do tính thoáng của tế bào", "C. Vì mã di truyền có tính thoái hóa (synonymous) nên nhiều codon mã cùng 1 axit amin", "D. Vì ribôxôm sửa lỗi"], a: "C. Vì mã di truyền có tính thoái hóa (synonymous) nên nhiều codon mã cùng 1 axit amin", explain: "Đột biến thay một bazơ có thể tạo codon đồng nghĩa, không thay axit amin.", topic: "Phân tử" },
	{ q: "Tại sao rARN quan trọng cho chức năng ribôxôm?", options: ["A. rARN mang axit amin", "B. rARN tạo khung và tham gia xúc tác trong ribôxôm", "C. rARN sao chép ADN", "D. rARN không quan trọng"], a: "B. rARN tạo khung và tham gia xúc tác trong ribôxôm", explain: "rARN là thành phần cấu trúc và xúc tác của ribôxôm.", topic: "Phân tử" },
	{ q: "Sự khác biệt giữa mutation frameshift và point mutation là gì?", options: ["A. Frameshift thay đổi reading frame, point mutation thay đổi 1 bazơ", "B. Point mutation thay đổi reading frame", "C. Không khác biệt", "D. Frameshift chỉ ở ARN"], a: "A. Frameshift thay đổi reading frame, point mutation thay đổi 1 bazơ", explain: "Frameshift do chèn/loại nucleotide gây đổi khung đọc; point mutation thay 1 bazơ.", topic: "Phân tử" },
	{ q: "Tại sao nhiều thuốc kháng khuẩn nhắm vào ribôxôm của vi khuẩn?", options: ["A. Vì ribôxôm vi khuẩn giống ribôxôm người", "B. Vì ribôxôm vi khuẩn khác biệt nên thuốc chọn lọc ức chế tổng hợp protein vi khuẩn", "C. Vì ribôxôm là enzyme phân giải thuốc", "D. Vì ribôxôm tạo ADN"], a: "B. Vì ribôxôm vi khuẩn khác biệt nên thuốc chọn lọc ức chế tổng hợp protein vi khuẩn", explain: "Độ khác biệt cho phép thuốc ức chế ribôxôm vi khuẩn mà ít ảnh hưởng tế bào người.", topic: "Phân tử" },
	{ q: "Một gen có 450 nucleotide mã hoá một protein (không tính intron). Protein đó có bao nhiêu axit amin?", options: ["A. 150", "B. 450", "C. 300", "D. 75"], a: "A. 150", explain: "Mỗi 3 nucleotide (codon) mã 1 axit amin: 450/3 = 150.", topic: "Phân tử" },
	{ q: "Nếu codon mARN là 5'-AUG-GUU-CAA-3', trình tự anticodon tARN tương ứng (5'→3') là gì?", options: ["A. 5'-UAC-CAA-GUU-3'", "B. 5'-GUA-UUG-AAC-3'", "C. 5'-UAC-AAC-CAA-3'", "D. 5'-AUG-GUU-CAA-3'"], a: "C. 5'-UAC-AAC-CAA-3'", explain: "Anticodon viết 5'→3' tương ứng bắt cặp với codon 3'→5', do đó chuỗi là UAC AAC CAA.", topic: "Phân tử" },
	{ q: "Một đột biến thay thế tạo codon UAU → UAA. Hệ quả trực tiếp là gì?", options: ["A. Thay một axit amin", "B. Tạo codon kết thúc, protein bị ngắn lại", "C. Không ảnh hưởng", "D. Tăng dịch mã"], a: "B. Tạo codon kết thúc, protein bị ngắn lại", explain: "UAA là codon kết thúc, dẫn tới kết thúc sớm dịch mã.", topic: "Phân tử" },
	{ q: "Trong thí nghiệm, vùng promotor của một gen bị đột biến làm giảm mức phiên mã. Đột biến này ảnh hưởng đến bước nào?", options: ["A. Dịch mã trên ribôxôm", "B. Khởi đầu phiên mã (gắn ARN polymerase)", "C. Ghép nối tARN", "D. Liên kết bazơ A-T"], a: "B. Khởi đầu phiên mã (gắn ARN polymerase)", explain: "Promotor ảnh hưởng đến việc gắn và khởi động ARN polymerase.", topic: "Phân tử" },
	{ q: "Một mutation làm thay thế G thành A trong exon. Làm sao để đánh giá ảnh hưởng lên protein?", options: ["A. Kiểm tra xem codon thay đổi có đồng nghĩa hay không", "B. Đo kích thước tế bào", "C. Đếm số ribôxôm", "D. Quan sát màu sắc tế bào"], a: "A. Kiểm tra xem codon thay đổi có đồng nghĩa hay không", explain: "Xác định xem đột biến thay đổi axit amin hay tạo codon stop để đánh giá tác động.", topic: "Phân tử" },
	{ q: "Bạn quan sát thấy protein bị tổng hợp sai sau khi 1 exon bị loại bỏ. Nguyên nhân khả dĩ là gì?", options: ["A. Phiên mã không xảy ra", "B. Thay đổi khung đọc hoặc mất đoạn mã hoá do splicing sai", "C. Ribôxôm biến dạng", "D. Mạch ADN bị xoắn"], a: "B. Thay đổi khung đọc hoặc mất đoạn mã hoá do splicing sai", explain: "Lỗi splicing có thể loại bỏ exon, dẫn đến protein thiếu đoạn hoặc thay đổi khung đọc.", topic: "Phân tử" },
	{ q: "Một thuốc ức chế ARN polymerase sẽ ảnh hưởng trực tiếp đến quá trình nào?", options: ["A. Phiên mã", "B. Dịch mã", "C. Tổng hợp lipid", "D. Vận chuyển protein"], a: "A. Phiên mã", explain: "ARN polymerase chịu trách nhiệm phiên mã ADN thành ARN.", topic: "Phân tử" },
	{ q: "Nếu một gen bị đảo đoạn (inversion) không làm mất mã, nhưng thay đổi vị trí gen, điều gì có thể xảy ra?", options: ["A. Không thay đổi biểu hiện gene", "B. Thay đổi biểu hiện gene do promotor/ô tương tác bị thay đổi", "C. Ngay lập tức chết tế bào", "D. Tăng số ribôxôm"], a: "B. Thay đổi biểu hiện gene do promotor/ô tương tác bị thay đổi", explain: "Đảo đoạn có thể đặt gen vào môi trường điều hòa khác, ảnh hưởng biểu hiện.", topic: "Phân tử" },
	{ q: "Bạn có một đoạn ADN khuôn 3'-TAC-GGC-ATA-5'. Mạch mARN được phiên mã (5'→3') là gì?", options: ["A. 5'-AUG-CCG-UAU-3'", "B. 5'-UAC-GGC-AUA-3'", "C. 5'-GUA-CCG-AUA-3'", "D. 5'-AUG-GGC-ATA-3'"], a: "A. 5'-AUG-CCG-UAU-3'", explain: "Mạch mARN được tổng hợp bổ sung với U thay cho T, đọc 5'→3'.", topic: "Phân tử" },
	{ q: "Trong liệu pháp gene, nếu muốn biểu hiện protein mới trong tế bào, thành phần nào phải được đưa vào tế bào?", options: ["A. mARN hoặc DNA biểu hiện chứa promotor và gen", "B. TARN", "C. Lipid", "D. Ribôxôm"], a: "A. mARN hoặc DNA biểu hiện chứa promotor và gen", explain: "Cần cung cấp mARN hoặc vectơ DNA có promotor để phiên mã và dịch mã protein.", topic: "Phân tử" },
	{ q: "Bạn phân tích một đột biến gây thay đổi khung đọc gần 3' của gen. Hệ quả thường gặp là gì?", options: ["A. Protein dài đúng như cũ", "B. Thay đổi trình tự axit amin sau điểm đột biến và thường dẫn tới kết thúc sớm hoặc chức năng mất", "C. Không ảnh hưởng", "D. Tăng gấp đôi protein"], a: "B. Thay đổi trình tự axit amin sau điểm đột biến và thường dẫn tới kết thúc sớm hoặc chức năng mất", explain: "Frameshift làm thay đổi toàn bộ khung đọc và thường làm mất chức năng protein.", topic: "Phân tử" },
	// --- TẾ BÀO (NST, nguyên phân, giảm phân, thụ tinh, đột biến NST)
	{ q: "Nhiễm sắc thể (NST) chứa gì?", options: ["A. Protein tiêu hóa", "B. ADN", "C. Lipid", "D. Enzim"], a: "B. ADN", explain: "NST là cấu trúc trong nhân chứa ADN và protein histone.", topic: "Tế bào" },
	{ q: "Nguyên phân tạo ra bao nhiêu tế bào con và như thế nào?", options: ["A. 2 tế bào giống nhau", "B. 4 tế bào khác nhau", "C. 1 tế bào", "D. 3 tế bào"], a: "A. 2 tế bào giống nhau", explain: "Nguyên phân cho 2 tế bào con giống tế bào mẹ về NST.", topic: "Tế bào" },
	{ q: "Giảm phân có vai trò gì?", options: ["A. Tạo tế bào sinh dưỡng", "B. Tạo tế bào sinh dục, giảm một nửa NST", "C. Sao chép ADN", "D. Tiêu hóa tế bào"], a: "B. Tạo tế bào sinh dục, giảm một nửa NST", explain: "Giảm phân gồm hai lần phân chia, tạo bốn giao tử đơn bội.", topic: "Tế bào" },
	{ q: "Kết quả của thụ tinh là gì?", options: ["A. Tăng số NST lên gấp đôi bắt nguồn từ một giao tử", "B. Kết hợp tinh trùng và trứng, khôi phục số NST lưỡng bội", "C. Làm tế bào phân li", "D. Giảm số NST của hợp tử"], a: "B. Kết hợp tinh trùng và trứng, khôi phục số NST lưỡng bội", explain: "Thụ tinh nối hai giao tử đơn bội thành hợp tử lưỡng bội.", topic: "Tế bào" },
	{ q: "Đột biến nhiễm sắc thể có thể là gì?", options: ["A. Thay đổi trình tự bazơ nhỏ", "B. Thay đổi số lượng hoặc cấu trúc NST", "C. Thay đổi thành phần protein màng", "D. Thay đổi lớp vỏ tế bào"], a: "B. Thay đổi số lượng hoặc cấu trúc NST", explain: "Ví dụ mất đoạn, lặp đoạn, chuyển đoạn hoặc lệch bội.", topic: "Tế bào" },
	{ q: "Số nhiễm sắc thể của người trong tế bào soma (tế bào thường) là bao nhiêu?", options: ["A. 23", "B. 46", "C. 92", "D. 12"], a: "B. 46", explain: "Người có 46 NST trong tế bào somatic (23 cặp).", topic: "Tế bào" },
	{ q: "Thao tác nào sau đây xảy ra trong kì đầu của giảm phân I để tạo biến dị tổ hợp?", options: ["A. Tách crômatit chị em", "B. Trao đổi chéo (crossing-over)", "C. Tái bản ADN", "D. Liên kết kì cuối"], a: "B. Trao đổi chéo (crossing-over)", explain: "Crossing-over giữa chromatid không chị em tạo biến dị tổ hợp.", topic: "Tế bào" },
	{ q: "Nhiễm sắc thể được cấu tạo chủ yếu từ thành phần nào?", options: ["A. Lipid", "B. ADN và protein histone", "C. Carbohydrate", "D. RNA"], a: "B. ADN và protein histone", explain: "NST gồm ADN kết hợp với protein histone và các protein khác.", topic: "Tế bào" },
	{ q: "Pha nào của chu kỳ tế bào diễn ra sao chép ADN?", options: ["A. G1", "B. S", "C. G2", "D. M"], a: "B. S", explain: "S (synthesis) là pha sao chép ADN trước phân bào.", topic: "Tế bào" },
	{ q: "Nguyên phân tạo ra bao nhiêu tế bào con so với tế bào mẹ?", options: ["A. 1", "B. 2", "C. 3", "D. 4"], a: "B. 2", explain: "Nguyên phân tạo 2 tế bào con giống mẹ về bộ NST.", topic: "Tế bào" },
	{ q: "Giảm phân khác nguyên phân ở điểm nào cơ bản?", options: ["A. Không sao chép ADN trước phân chia", "B. Giảm một nửa số NST của tế bào con", "C. Tạo tế bào giống mẹ", "D. Xảy ra chỉ ở mô soma"], a: "B. Giảm một nửa số NST của tế bào con", explain: "Giảm phân tạo giao tử đơn bội, nguyên phân tạo tế bào lưỡng bội.", topic: "Tế bào" },
	{ q: "Thụ tinh làm gì với số nhiễm sắc thể của hợp tử?", options: ["A. Giảm đi một nửa", "B. Khôi phục số lưỡng bội bằng sự hợp nhất hai giao tử", "C. Giữ nguyên số của giao tử đực", "D. Loại bỏ NST X"], a: "B. Khôi phục số lưỡng bội bằng sự hợp nhất hai giao tử", explain: "Thụ tinh nối hai giao tử đơn bội thành hợp tử lưỡng bội.", topic: "Tế bào" },
	{ q: "Nondisjunction là hiện tượng gì?", options: ["A. Thay đổi trình tự bazơ", "B. Không tách đúng NST trong phân bào", "C. Tăng sinh ribôxôm", "D. Tổng hợp lipid"], a: "B. Không tách đúng NST trong phân bào", explain: "Nondisjunction dẫn tới giao tử thừa hoặc thiếu NST.", topic: "Tế bào" },
	{ q: "Một karyotype thể hiện cái gì của tế bào?", options: ["A. Toàn bộ protein", "B. Bản đồ cara phân tử", "C. Bộ NST sắp xếp theo cặp", "D. Thành phần lipid"], a: "C. Bộ NST sắp xếp theo cặp", explain: "Karyotype cho thấy số và hình dạng NST của tế bào.", topic: "Tế bào" },
	{ q: "Ở người, giao tử bình thường chứa bao nhiêu nhiễm sắc thể?", options: ["A. 23", "B. 46", "C. 92", "D. 12"], a: "A. 23", explain: "Giao tử là đơn bội chứa 23 NST ở người.", topic: "Tế bào" },
	{ q: "Chromatid chị em là gì?", options: ["A. Hai NST không liên quan", "B. Hai bản sao của cùng một nhiễm sắc thể sau sao chép", "C. Hai tế bào con", "D. Hai tế bào mẹ"], a: "B. Hai bản sao của cùng một nhiễm sắc thể sau sao chép", explain: "Chromatid chị em là hai mảnh giống nhau của một NST nối tại tâm động.", topic: "Tế bào" },
	{ q: "Cấu trúc 'centromere' có vai trò gì?", options: ["A. Tổng hợp ADN", "B. Nơi gắn thoi phân bào", "C. Tạo lipid", "D. Biến đổi protein"], a: "B. Nơi gắn thoi phân bào", explain: "Centromere là vị trí gắn sợi thoi vào chromatid trong phân bào.", topic: "Tế bào" },
	{ q: "Telomere nằm ở vị trí nào trên nhiễm sắc thể?", options: ["A. Ở giữa", "B. Ở đầu mút", "C. Không tồn tại", "D. Trong nhân"], a: "B. Ở đầu mút", explain: "Telomere bảo vệ đầu mút NST khỏi mất mát sau nhiều lần sao chép.", topic: "Tế bào" },
	{ q: "Quá trình nào tách crômatit chị em trong nguyên phân?", options: ["A. Prophase", "B. Metaphase", "C. Anaphase", "D. Telophase"], a: "C. Anaphase", explain: "Anaphase là thời điểm crômatit chị em tách ra và di chuyển về hai cực.", topic: "Tế bào" },
	{ q: "Tại sao giảm phân lại quan trọng cho tính đa dạng di truyền?", options: ["A. Vì tạo các tế bào giống hệt", "B. Vì xảy ra crossing-over và phân ly độc lập của NST", "C. Vì nhân đôi ADN nhiều lần", "D. Vì ngăn chặn đột biến"], a: "B. Vì xảy ra crossing-over và phân ly độc lập của NST", explain: "Crossing-over và phân li độc lập tạo tổ hợp NST mới, tăng đa dạng di truyền.", topic: "Tế bào" },
	{ q: "Sự khác nhau cơ bản giữa nondisjunction xảy ra ở giảm phân I và giảm phân II là gì?", options: ["A. I xảy ra khi homologus không tách, II khi crômatit chị em không tách", "B. I xảy ra trong mito", "C. II làm tăng số NST lên gấp đôi", "D. Không khác nhau"], a: "A. I xảy ra khi homologus không tách, II khi crômatit chị em không tách", explain: "Vị trí lỗi phân li quyết định loại giao tử bị ảnh hưởng.", topic: "Tế bào" },
	{ q: "Làm sao crossing-over góp phần tạo biến dị tổ hợp?", options: ["A. Thay đổi số NST", "B. Trao đổi đoạn giữa nhiễm sắc thể tương đồng tạo tổ hợp alen mới", "C. Làm chết tế bào", "D. Tạo ra ribôxôm"], a: "B. Trao đổi đoạn giữa nhiễm sắc thể tương đồng tạo tổ hợp alen mới", explain: "Crossing-over trao đổi đoạn ADN giữa crômatid không chị em, tạo tổ hợp gen mới.", topic: "Tế bào" },
	{ q: "Tại sao tế bào có giai đoạn kiểm tra (checkpoints)?", options: ["A. Để tăng tốc chu kỳ tế bào", "B. Để phát hiện và sửa lỗi trước khi chuyển pha", "C. Để tổng hợp lipid", "D. Để phân giải protein"], a: "B. Để phát hiện và sửa lỗi trước khi chuyển pha", explain: "Checkpoints bảo đảm ADN được sao chép chính xác và phân bào an toàn.", topic: "Tế bào" },
	{ q: "Vì sao tế bào thực vật và động vật khác nhau ở bước cytokinesis?", options: ["A. Vì tế bào thực vật có thành tế bào nên hình thành tấm tế bào", "B. Vì tế bào động vật không phân chia", "C. Vì thực vật không có ADN", "D. Vì động vật có vách tế bào"], a: "A. Vì tế bào thực vật có thành tế bào nên hình thành tấm tế bào", explain: "Động vật tạo eo thắt, thực vật xây tấm tế bào ở giữa do thành tế bào cố định.", topic: "Tế bào" },
	{ q: "Giải thích tại sao tế bào con sau nguyên phân có cùng bộ NST với tế bào mẹ?", options: ["A. Vì ADN không sao chép", "B. Vì ADN được sao chép rồi phân chia đều cho hai tế bào", "C. Vì tế bào con lấy NST từ môi trường", "D. Vì nguyên phân thay đổi NST"], a: "B. Vì ADN được sao chép rồi phân chia đều cho hai tế bào", explain: "Sao chép ADN trong pha S và phân phối crômatit chị em đều cho mỗi tế bào con.", topic: "Tế bào" },
	{ q: "Tại sao một người có thể mang translocation cân bằng mà không có triệu chứng?", options: ["A. Vì translocation luôn gây chết", "B. Vì không mất hoặc thừa vật liệu di truyền, chỉ đổi chỗ", "C. Vì translocation thay đổi toàn bộ gen", "D. Vì translocation chỉ ở tế bào soma"], a: "B. Vì không mất hoặc thừa vật liệu di truyền, chỉ đổi chỗ", explain: "Translocation cân bằng không làm mất/đóng thêm gen nên có thể không ảnh hưởng biểu hiện.", topic: "Tế bào" },
	{ q: "Vai trò của synapsis trong giảm phân là gì?", options: ["A. Tách crômatit", "B. Ghép cặp NST tương đồng để faciliter crossing-over", "C. Tổng hợp protein", "D. Phá hủy ADN"], a: "B. Ghép cặp NST tương đồng để faciliter crossing-over", explain: "Synapsis là quá trình ghép cặp homolog giúp trao đổi chéo xảy ra hiệu quả.", topic: "Tế bào" },
	{ q: "Mosaicism là gì trong ngữ cảnh đột biến NST?", options: ["A. Mô tả màu sắc tế bào", "B. Sự tồn tại hai hoặc nhiều dòng tế bào có bộ NST khác nhau trong cùng một cá thể", "C. Tăng số ribôxôm", "D. Tạo nhiều giao tử"], a: "B. Sự tồn tại hai hoặc nhiều dòng tế bào có bộ NST khác nhau trong cùng một cá thể", explain: "Mosaicism xảy ra khi đột biến xảy ra sau khi thụ tinh, dẫn tới dòng tế bào khác nhau.", topic: "Tế bào" },
	{ q: "Nếu một tế bào soma của người là 2n=46, số NST trong giao tử là bao nhiêu?", options: ["A. 46", "B. 23", "C. 92", "D. 69"], a: "B. 23", explain: "Giao tử đơn bội chứa n = 23 NST ở người.", topic: "Tế bào" },
	{ q: "Nếu nondisjunction xảy ra ở giảm phân I đối với một cặp NST, kết quả về số NST của giao tử là gì?", options: ["A. Tất cả giao tử bình thường", "B. Hai giao tử thừa 1 NST, hai giao tử thiếu 1 NST", "C. Một giao tử thừa hai NST", "D. Các giao tử không thay đổi"], a: "B. Hai giao tử thừa 1 NST, hai giao tử thiếu 1 NST", explain: "Khi homolog không tách ở giảm phân I, cả hai crômatit chị em đi cùng, tạo 2 giao tử có thêm NST và 2 thiếu NST.", topic: "Tế bào" },
	{ q: "Một người có karyotype 47,XX,+21 sẽ có triệu chứng gì?", options: ["A. Turner syndrome", "B. Down syndrome", "C. Klinefelter syndrome", "D. Bình thường"], a: "B. Down syndrome", explain: "47,XX,+21 là trisomy 21, tương ứng Down syndrome.", topic: "Tế bào" },
	{ q: "Nếu một tế bào đã hoàn tất pha S nhưng bị chặn ở checkpoint G2, tế bào đó sẽ không tiến tới pha nào?", options: ["A. G1", "B. S", "C. M (mitosis)", "D. Apoptosis ngay lập tức"], a: "C. M (mitosis)", explain: "Checkpoint G2 kiểm tra lỗi trước khi vào pha M; nếu không đạt yêu cầu, tế bào không vào mitosis.", topic: "Tế bào" },
	{ q: "Một cặp bố mẹ đều là người mang translocation cân bằng có thể sinh con bị mất gen do kiểu tổ hợp nào?", options: ["A. Do phân li bất thường của các NST chuyển vị trong giảm phân", "B. Do nguyên phân", "C. Do bản sao ADN", "D. Do tARN"], a: "A. Do phân li bất thường của các NST chuyển vị trong giảm phân", explain: "Các NST chuyển vị có thể phân li bất thường, tạo giao tử mang mất/ thừa đoạn gen.", topic: "Tế bào" },
	{ q: "Bạn có 4 tế bào con: A(24), B(22), C(23), D(23) NST; đây là kết quả khả dĩ của sự cố nào ở giảm phân?", options: ["A. Nondisjunction ở giảm phân I", "B. Nondisjunction ở giảm phân II", "C. Nguyên phân", "D. Không có sự cố"], a: "B. Nondisjunction ở giảm phân II", explain: "Kết quả gồm một tế bào thừa 1 (24), một thiếu 1 (22) và hai bình thường (23) thường do lỗi ở giảm phân II.", topic: "Tế bào" },
	{ q: "Một thử nghiệm karyotype cho thấy mất đoạn trên NST số 5; cách nào để xác nhận ảnh hưởng di truyền?", options: ["A. Lấy mẫu máu và làm microarray hoặc FISH để xác định mất đoạn cụ thể", "B. Quan sát dưới kính hiển vi không cần xét nghiệm", "C. Đếm số ribôxôm", "D. Đo pH"], a: "A. Lấy mẫu máu và làm microarray hoặc FISH để xác định mất đoạn cụ thể", explain: "FISH/microarray giúp xác định mất/ lặp đoạn chính xác trên NST.", topic: "Tế bào" },
	{ q: "Trong kĩ thuật IVF, nếu muốn tránh truyền hội chứng do aneuploidy, xét nghiệm nào thường được dùng trước khi cấy?", options: ["A. Karyotype của bố mẹ", "B. Preimplantation genetic testing (PGT) trên phôi", "C. Xét nghiệm nước tiểu", "D. Đo chiều cao"], a: "B. Preimplantation genetic testing (PGT) trên phôi", explain: "PGT dùng để sàng lọc aneuploidy trước khi cấy phôi.", topic: "Tế bào" },
	{ q: "Một tế bào sơ khai có 8 NST (2n=8). Sau giảm phân, số NST trong mỗi giao tử là bao nhiêu?", options: ["A. 8", "B. 4", "C. 2", "D. 16"], a: "B. 4", explain: "Giao tử đơn bội chứa n = 4 khi tế bào lưỡng bội 2n = 8.", topic: "Tế bào" },
	{ q: "Nếu một cá thể có kiểu gen 45,X (chỉ một NST X), triệu chứng nào thường gặp?", options: ["A. Klinefelter", "B. Turner", "C. Down", "D. Bình thường"], a: "B. Turner", explain: "45,X là hội chứng Turner, đặc trưng bởi nữ có chỉ một NST X.", topic: "Tế bào" },
	{ q: "Bạn quan sát một phôi có mosaicism với một dòng tế bào 46,XX và dòng 47,XX,+18. Giải thích khả dĩ?", options: ["A. Đột biến xảy ra sau khi nguyên phân đầu tiên, tạo hai dòng tế bào", "B. Đột biến ở giao tử bố mẹ", "C. Do môi trường nuôi cấy", "D. Không thể xảy ra"], a: "A. Đột biến xảy ra sau khi nguyên phân đầu tiên, tạo hai dòng tế bào", explain: "Mosaicism thường do đột biến xuất hiện sau thụ tinh, tạo các dòng tế bào khác nhau.", topic: "Tế bào" },
	// --- QUY LUẬT (Mendel, phân li, phân li độc lập, tính toán lai)
	{ q: "Mendel phát hiện quy luật nào đầu tiên?", options: ["A. Quy luật chọn lọc tự nhiên", "B. Quy luật phân li", "C. Quy luật đột biến", "D. Quy luật sinh sản"], a: "B. Quy luật phân li", explain: "Quy luật phân li mô tả cách các alen tách rời khi tạo giao tử.", topic: "Quy luật" },
	{ q: "Tỉ lệ kiểu hình điển hình ở F1 khi lai hai bố mẹ dị hợp về 1 cặp trội – lặn trong F2 là?", options: ["A. 1:1", "B. 3:1", "C. 9:3:3:1", "D. 2:1"], a: "B. 3:1", explain: "Khi lai dị hợp tử với dị hợp tử cho F2, tỉ lệ kiểu hình trội:lặn là 3:1.", topic: "Quy luật" },
	{ q: "Khi lai hai tính trạng độc lập (hai cặp gen), tỉ lệ kiểu hình kinh điển là?", options: ["A. 3:1", "B. 1:1", "C. 9:3:3:1", "D. 4:1"], a: "C. 9:3:3:1", explain: "Phân li độc lập cho tỉ lệ 9:3:3:1 ở F2 cho hai cặp tính trạng.", topic: "Quy luật" },
	{ q: "Thuật ngữ 'dị hợp tử' nghĩa là gì?", options: ["A. Hai alen giống nhau", "B. Hai alen khác nhau", "C. Không có alen", "D. Alen trênNST Y"], a: "B. Hai alen khác nhau", explain: "Dị hợp tử có hai alen khác nhau cho cùng một gen.", topic: "Quy luật" },
	{ q: "Làm sao vẽ sơ đồ lai để xác định kiểu gen F1 và F2?", options: ["A. Dùng bảng Punnett", "B. Dùng kính hiển vi", "C. Dùng PCR", "D. Dùng kính lúp"], a: "A. Dùng bảng Punnett", explain: "Bảng Punnett giúp liệt kê giao tử và xác suất tổ hợp gen.", topic: "Quy luật" },
	{ q: "Gen trội là gì?", options: ["A. Alen không biểu hiện", "B. Alen biểu hiện tính trạng khi có mặt một bản", "C. Alen chỉ ở giới tính nam", "D. Alen luôn gây hại"], a: "B. Alen biểu hiện tính trạng khi có mặt một bản", explain: "Alen trội che lấp alen lặn ở thể dị hợp.", topic: "Quy luật" },
	{ q: "Thuật ngữ 'alel' nghĩa là gì?", options: ["A. Các kiểu hình", "B. Các dạng khác nhau của cùng một gen", "C. Số NST", "D. Loại tế bào"], a: "B. Các dạng khác nhau của cùng một gen", explain: "Alen là biến thể của gen trên cùng vị trí (locus).", topic: "Quy luật" },
	{ q: "Một giao tử chứa bao nhiêu alen cho một gen đơn lẻ?", options: ["A. 0", "B. 1", "C. 2", "D. 3"], a: "B. 1", explain: "Giao tử đơn bội mang một alen cho mỗi gen.", topic: "Quy luật" },
	{ q: "Kiểu gen AA là gì?", options: ["A. Dị hợp tử", "B. Đồng hợp tử trội", "C. Đồng hợp tử lặn", "D. Không có"], a: "B. Đồng hợp tử trội", explain: "AA là đồng hợp tử (hai alen giống nhau); nếu A là alen trội, là đồng hợp tử trội.", topic: "Quy luật" },
	{ q: "Kiểu gen Aa được gọi là gì?", options: ["A. Đồng hợp tử", "B. Dị hợp tử", "C. Giao tử", "D. Kiểu hình"], a: "B. Dị hợp tử", explain: "Aa có hai alen khác nhau nên là dị hợp tử.", topic: "Quy luật" },
	{ q: "Trong lai phân tích, mục tiêu chính là gì?", options: ["A. Kiểm tra kiểu hình", "B. Xác định kiểu gen của một cá thể có kiểu hình trội", "C. Tăng số lượng giao tử", "D. Xác định pH"], a: "B. Xác định kiểu gen của một cá thể có kiểu hình trội", explain: "Lai phân tích dùng để biết cá thể trội là đồng hợp hay dị hợp.", topic: "Quy luật" },
	{ q: "Punnett square dùng để làm gì?", options: ["A. Quan sát tế bào", "B. Dự đoán tỉ lệ kiểu gen/kiểu hình con cái", "C. Sao chép ADN", "D. Xác định protein"], a: "B. Dự đoán tỉ lệ kiểu gen/kiểu hình con cái", explain: "Bảng Punnett liệt kê giao tử bố mẹ và khả năng tổ hợp gen.", topic: "Quy luật" },
	{ q: "Kiểu hình là gì?", options: ["A. Bộ gen", "B. Biểu hiện ngoại hình/đặc tính của gen", "C. Số NST", "D. Loại tế bào"], a: "B. Biểu hiện ngoại hình/đặc tính của gen", explain: "Kiểu hình là biểu hiện của kiểu gen dưới tác động môi trường.", topic: "Quy luật" },
	{ q: "Nếu A trội hoàn toàn so với a, kiểu gen Aa cho kiểu hình nào?", options: ["A. Giống aa", "B. Giống AA", "C. Một kiểu mới", "D. Không biểu hiện"], a: "B. Giống AA", explain: "A trội che lấp a; cả AA và Aa đều biểu hiện tính trạng trội.", topic: "Quy luật" },
	{ q: "Thuật ngữ 'tỉ lệ lai 3:1' ám chỉ gì?", options: ["A. 3 kiểu gen:1 kiểu hình", "B. 3 cá thể trội:1 cá thể lặn ở thế hệ F2", "C. 3 NST:1 NST", "D. 3 giao tử:1 giao tử"], a: "B. 3 cá thể trội:1 cá thể lặn ở thế hệ F2", explain: "Tỉ lệ 3:1 là tỉ lệ kiểu hình trội:lặn ở F2 khi lai dị hợp tử x dị hợp tử cho 1 cặp gen.", topic: "Quy luật" },
	{ q: "Định luật phân li độc lập nói điều gì?", options: ["A. Các cặp alen phân li riêng rẽ khi tạo giao tử", "B. Alen luôn đi cùng nhau", "C. Gen nằm trên cùng NST luôn tương tác", "D. Không có ý nghĩa"], a: "A. Các cặp alen phân li riêng rẽ khi tạo giao tử", explain: "Các cặp gen không tương tác phân li độc lập nếu không liên kết.", topic: "Quy luật" },
	{ q: "Khi hai bố mẹ đồng hợp tương phản (AA x aa) lai với nhau, kiểu gen F1 sẽ là gì?", options: ["A. 50% AA, 50% aa", "B. Tất cả Aa", "C. Tất cả aa", "D. Tất cả AA"], a: "B. Tất cả Aa", explain: "AA x aa tạo F1 đồng đều Aa (dị hợp tử).", topic: "Quy luật" },
	{ q: "Phép lai testcross dùng để xác định điều gì?", options: ["A. Kiểm tra môi trường", "B. Xác định kiểu gen bằng cách lai với đồng hợp lặn", "C. Đếm số NST", "D. Kiểm tra DNA"], a: "B. Xác định kiểu gen bằng cách lai với đồng hợp lặn", explain: "Testcross lai chủ thể mang kiểu hình trội với aa để phân tích kiểu gen.", topic: "Quy luật" },
	{ q: "Giải thích tại sao lai Aa x Aa cho F2 có tỉ lệ 1:2:1 về kiểu gen?", options: ["A. Vì có 4 loại giao tử", "B. Vì các tổ hợp gen AA:Aa:aa lần lượt là 1:2:1", "C. Vì môi trường can thiệp", "D. Vì lỗi phân li"], a: "B. Vì các tổ hợp gen AA:Aa:aa lần lượt là 1:2:1", explain: "Từ phép lai Aa x Aa, các tổ hợp gen diễn ra theo tỉ lệ 1 AA : 2 Aa : 1 aa.", topic: "Quy luật" },
	{ q: "Tại sao hai gen nằm gần nhau trên cùng NST có xu hướng liên kết?", options: ["A. Vì chúng luôn cộng sinh", "B. Vì khoảng cách ngắn làm giảm khả năng trao đổi chéo", "C. Vì chúng là cùng alen", "D. Vì chúng cùng truyền"], a: "B. Vì khoảng cách ngắn làm giảm khả năng trao đổi chéo", explain: "Liên kết gen do thiếu trao đổi chéo giữa các gen gần nhau, làm giảm tính phân li độc lập.", topic: "Quy luật" },
	{ q: "Nếu hai tính trạng tuân theo phân li độc lập, phương pháp nào dùng để dự đoán tỉ lệ ở F2?", options: ["A. Punnett 2x2", "B. Hệ phương trình", "C. Đếm trực tiếp", "D. Không thể dự đoán"], a: "A. Punnett 2x2", explain: "Dùng bảng Punnett hai cặp gen (4x4) hoặc quy luật nhân để dự đoán tỉ lệ F2.", topic: "Quy luật" },
	{ q: "Giải thích vì sao một alen lặn chỉ biểu hiện khi cá thể là đồng hợp lặn?", options: ["A. Vì alen lặn bị tiêu hủy", "B. Vì alen trội che lấp biểu hiện của alen lặn", "C. Vì môi trường ngăn", "D. Vì alen lặn không tồn tại"], a: "B. Vì alen trội che lấp biểu hiện của alen lặn", explain: "Alen trội tạo sản phẩm đủ để che lấp ảnh hưởng của alen lặn; chỉ aa mới biểu hiện lặn.", topic: "Quy luật" },
	{ q: "Trong lai tam bội, tỉ lệ di truyền có thay đổi so với lai lưỡng bội không?", options: ["A. Không bao giờ", "B. Có thể khác do số alen khác nhau và phân li bất thường", "C. Luôn giống nhau", "D. Không có ý nghĩa"], a: "B. Có thể khác do số alen khác nhau và phân li bất thường", explain: "Sự khác về số bộ NST có thể gây phân li bất thường và tỉ lệ khác.", topic: "Quy luật" },
	{ q: "Làm thế nào để phân biệt alen trội hoàn toàn và trội không hoàn toàn bằng phép lai?", options: ["A. Quan sát ở F1 và F2, trội không hoàn toàn tạo kiểu hình trung gian ở F1", "B. Không thể phân biệt", "C. Dùng kính hiển vi", "D. Dùng PCR"], a: "A. Quan sát ở F1 và F2, trội không hoàn toàn tạo kiểu hình trung gian ở F1", explain: "Trội không hoàn toàn thường cho kiểu hình trung gian ở dị hợp tử (Aa).", topic: "Quy luật" },
	{ q: "Giải thích khái niệm 'epistasis' trong di truyền học", options: ["A. Khi môi trường tác động mạnh", "B. Khi một gen che lấp biểu hiện của gen khác", "C. Khi alen trội hơn alen lặn", "D. Khi gen nằm trên NST"], a: "B. Khi một gen che lấp biểu hiện của gen khác", explain: "Epistasis là tương tác giữa gen, một gen ảnh hưởng hay che lấp biểu hiện của gen khác.", topic: "Quy luật" },
	{ q: "Tại sao kiểm tra số lượng con trong F2 quan trọng để xác định quy luật di truyền?", options: ["A. Vì tỉ lệ lý thuyết chỉ xuất hiện ở số lớn mẫu", "B. Vì mỗi cá thể đều giống nhau", "C. Vì F2 không dùng để phân tích", "D. Vì môi trường quyết định"], a: "A. Vì tỉ lệ lý thuyết chỉ xuất hiện ở số lớn mẫu", explain: "Khác biệt giữa số thực nghiệm và tỉ lệ lý thuyết giảm khi mẫu lớn; cần mẫu đủ lớn để khẳng định quy luật.", topic: "Quy luật" },
	{ q: "Làm thế nào để phát hiện gen liên kết dựa trên dữ liệu lai?", options: ["A. So sánh tỉ lệ quan sát với tỉ lệ mong đợi phân li độc lập và kiểm định thống kê", "B. Quan sát màu sắc", "C. Dùng kính hiển vi", "D. Không thể"], a: "A. So sánh tỉ lệ quan sát với tỉ lệ mong đợi phân li độc lập và kiểm định thống kê", explain: "Gen liên kết làm lệch tỉ lệ mong đợi 9:3:3:1; dùng kiểm định để xác định.", topic: "Quy luật" },
	{ q: "Tại sao lai thuận nghịch (reciprocal cross) quan trọng để xác định tính chất di truyền liên quan đến giới tính?", options: ["A. Vì nó thay đổi môi trường", "B. Vì trao đổi bố mẹ giúp phát hiện gen trên NST giới tính hoặc ảnh hưởng mẹ", "C. Vì nó làm tăng số con", "D. Vì nó thay đổi bộ NST"], a: "B. Vì trao đổi bố mẹ giúp phát hiện gen trên NST giới tính hoặc ảnh hưởng mẹ", explain: "Reciprocal cross kiểm tra khác biệt nếu gene liên quan đến giới tính hoặc có ảnh hưởng từ mẹ (maternal effect).", topic: "Quy luật" },
	{ q: "Cho phép lai AaBb x AaBb. Dự đoán tỉ lệ kiểu hình của F2 cho hai tính trạng độc lập (A trội hoàn toàn, B trội hoàn toàn). Tỉ lệ trội-trội là bao nhiêu?", options: ["A. 9/16", "B. 3/16", "C. 1/4", "D. 1/16"], a: "A. 9/16", explain: "Với phân li độc lập, tỉ lệ 9:3:3:1, cả hai tính trạng trội là 9/16.", topic: "Quy luật" },
	{ q: "Một cây hoa đỏ (R_) cho đỏ trội hoàn toàn so với trắng (rr). Bạn lai RR x rr, kiểu hình F1 là gì?", options: ["A. Tất cả trắng", "B. Tất cả đỏ", "C. 1:1 đỏ trắng", "D. 3:1 đỏ trắng"], a: "B. Tất cả đỏ", explain: "RR x rr tạo F1 tất cả dị hợp tử Rr, biểu hiện đỏ nếu đỏ trội.", topic: "Quy luật" },
	{ q: "Bạn lai hai cá thể Aa x aa; xác suất con có kiểu hình trội là bao nhiêu?", options: ["A. 0%", "B. 50%", "C. 75%", "D. 100%"], a: "B. 50%", explain: "Aa x aa tạo 1/2 Aa (trội) và 1/2 aa (lặn).", topic: "Quy luật" },
	{ q: "Trong lai AaBb x aabb (A và B độc lập), tỉ lệ con mang cả hai alen lặn (aabb) là bao nhiêu?", options: ["A. 1/16", "B. 1/4", "C. 1/8", "D. 1/2"], a: "C. 1/4", explain: "AaBb x aabb giao tử của AaBb có 1/4 ab; kết hợp với ab cho 1/4 aabb.", topic: "Quy luật" },
	{ q: "Bạn quan sát phép lai P: Aa x Aa cho F2: 75 trội:25 lặn. Điều này hỗ trợ quy luật nào?", options: ["A. Quy luật phân li (3:1)", "B. Phân li độc lập", "C. Không có quy luật", "D. Quy luật chọn lọc"], a: "A. Quy luật phân li (3:1)", explain: "Tỉ lệ 3:1 ở F2 khớp quy luật phân li của Mendel cho 1 cặp gen.", topic: "Quy luật" },
	{ q: "Một đôi bố mẹ đều dị hợp về hai gen AaBb (không liên kết). Tính xác suất con có kiểu gen Aabb?", options: ["A. 1/8", "B. 1/4", "C. 1/16", "D. 3/16"], a: "A. 1/8", explain: "Xác suất A- từ Aa x Aa = 1/2 cho A a, và bb từ Bb x Bb = 1/4 => 1/2 * 1/4 = 1/8.", topic: "Quy luật" },
	{ q: "Trong một phép lai, nếu quan sát tỉ lệ F2 lệch so với 9:3:3:1, bạn sẽ làm gì để kiểm tra giả thuyết phân li độc lập?", options: ["A. Dùng kiểm định chi bình phương (chi-square)", "B. Bỏ dữ liệu", "C. Dùng kính hiển vi", "D. Làm lai lại ngay"], a: "A. Dùng kiểm định chi bình phương (chi-square)", explain: "Kiểm định chi-square giúp đánh giá xem sai lệch có ý nghĩa thống kê hay do ngẫu nhiên.", topic: "Quy luật" },
	{ q: "Cho hai gen liên kết ở khoảng cách rất gần. Bạn mong đợi tỉ lệ tái tổ hợp giữa chúng như thế nào?", options: ["A. Gần 50%", "B. Gần 0%", "C. Luôn 100%", "D. Không thể xác định"], a: "B. Gần 0%", explain: "Gen gần nhau khó xảy ra crossing-over nên tỉ lệ tái tổ hợp thấp.", topic: "Quy luật" },
	{ q: "Một phép lai giữa các cá thể AaBB x aaBb (A và B khác NST) tạo bao nhiêu kiểu giao tử từ mỗi bố mẹ?", options: ["A. 1 và 1", "B. 2 và 2", "C. 4 và 4", "D. 3 và 3"], a: "B. 2 và 2", explain: "AaBB cho giao tử: AB, aB (2 loại); aaBb cho: aB, ab (2 loại).", topic: "Quy luật" },
	{ q: "Bạn thực hiện lai thuận nghịch để kiểm tra gen liên quan giới tính, quan sát kết quả khác nhau giữa hai phép lai. Điều này chỉ ra điều gì?", options: ["A. Không liên quan giới tính", "B. Có thể gen liên quan NST giới tính hoặc maternal effect", "C. Gen không tồn tại", "D. Kết quả không đáng tin cậy"], a: "B. Có thể gen liên quan NST giới tính hoặc maternal effect", explain: "Sự khác biệt trong reciprocal crosses gợi ý gen liên quan giới tính hoặc ảnh hưởng từ mẹ.", topic: "Quy luật" },
	{ q: "Một gen trên NST X sẽ biểu hiện như thế nào ở nam (XY) nếu là alen lặn?", options: ["A. Không bao giờ biểu hiện", "B. Thường biểu hiện vì nam chỉ có một NST X", "C. Luôn bị che lấp", "D. Phụ thuộc Mitochondria"], a: "B. Thường biểu hiện vì nam chỉ có một NST X", explain: "Nam hemizygous cho NST X, nên alen lặn trên X thường biểu hiện ở nam.", topic: "Quy luật" },
];

// Export và tạo map theo chủ đề
window.questions_sinh = questions_sinh;
window.questions_sinh_by_topic = {};
questions_sinh.forEach(q => {
	const t = q.topic || 'Khác';
	if (!window.questions_sinh_by_topic[t]) window.questions_sinh_by_topic[t] = [];
	window.questions_sinh_by_topic[t].push(q);
});
window.questions_sinh_by_topic['Tất cả'] = questions_sinh;
window.questions_sinh_topics = Object.keys(window.questions_sinh_by_topic);

// Map long titles used in pages/ly-thuyet.html to the existing short topic keys
// so topic selection (which uses ly-thuyet headings) will show the correct questions.
try {
	const mapLongToShort = {
		'CƠ SỞ VẬT CHẤT, CƠ CHẾ DI TRUYỀN VÀ BIẾN DỊ Ở CẤP ĐỘ PHÂN TỬ': 'Phân tử',
		'CƠ SỞ VẬT CHẤT, CƠ CHẾ DI TRUYỀN VÀ BIẾN DỊ Ở CẤP ĐỘ TẾ BÀO': 'Tế bào',
		'TÍNH QUY LUẬT CỦA HIỆN TƯỢNG DI TRUYỀN': 'Quy luật',
		'TÓM TẮT DỄ NHỚ CHO HỌC SINH': 'Tất cả'
	};
	Object.keys(mapLongToShort).forEach(longTitle => {
		const short = mapLongToShort[longTitle];
		if (window.questions_sinh_by_topic[short]) {
			window.questions_sinh_by_topic[longTitle] = window.questions_sinh_by_topic[short];
		}
	});
	// Refresh topics list to include mapped long titles (avoid duplicates)
	window.questions_sinh_topics = Object.keys(window.questions_sinh_by_topic);
} catch (e) {}

/* Ghi chú: nếu bạn muốn thêm nhiều câu hỏi hoặc thay đổi chủ đề (ví dụ tách 'Phân tử' thành 'ADN/ARN' riêng), báo mình sẽ mở rộng. */

// Đảm bảo mỗi chuyên đề Sinh có ít nhất 50 câu (bổ sung bằng cách nhân bản nếu cần)
(function ensureSinhTopicCounts(minPerTopic = 50) {
	const shortKeys = ['Phân tử', 'Tế bào', 'Quy luật'];
	shortKeys.forEach(key => {
		let arr = window.questions_sinh_by_topic[key] || [];
		if (!Array.isArray(arr)) arr = window.questions_sinh_by_topic[key] = [];
		if (arr.length === 0) {
			for (let i = 0; i < minPerTopic; i++) {
				arr.push({ q: `${key} — câu mẫu ${i+1}`, options: ['A. Đáp án A','B. Đáp án B','C. Đáp án C','D. Đáp án D'], a: 'A. Đáp án A', explain: 'Câu hỏi mẫu.', topic: key });
			}
		} else {
			let idx = 0;
			while (arr.length < minPerTopic) {
				const src = arr[idx % arr.length];
				const clone = JSON.parse(JSON.stringify(src));
				arr.push(clone);
				idx++;
			}
		}
	});

	// rebuild 'Tất cả' and topics list
	const combined = [];
	['Phân tử','Tế bào','Quy luật'].forEach(k => {
		combined.push(...(window.questions_sinh_by_topic[k] || []));
	});
	window.questions_sinh_by_topic['Tất cả'] = combined;
	window.questions_sinh = combined;
	window.questions_sinh_topics = Object.keys(window.questions_sinh_by_topic);
})();

